appName: Student-Course Database System

database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: (your mysql username)

  # the password
  password: (your mysql password)

  # the JDBC URL
  url: jdbc:mysql://localhost/courses
  

