appName: Student-Course Database System

database:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

  # the username
  user: root

  # the password
  password: sarthak1997

  # the JDBC URL
  url: jdbc:mysql://localhost/courses
  

